CREATE TABLE tx_aiscareer_domain_model_job (
  uid int(11) unsigned NOT NULL auto_increment,
  pid int(11) unsigned NOT NULL DEFAULT 0,
  title varchar(255) NOT NULL DEFAULT '',
  reference varchar(255) NOT NULL DEFAULT '',
  slug varchar(2048) NOT NULL DEFAULT '',
  description text,
  responsibilities text,
  qualifications text,
  benefits text,
  country varchar(16) NOT NULL DEFAULT '',
  city varchar(255) NOT NULL DEFAULT '',
  location_label varchar(255) NOT NULL DEFAULT '',
  department varchar(255) NOT NULL DEFAULT '',
  contract_type varchar(255) NOT NULL DEFAULT '',
  remote_possible tinyint(1) NOT NULL DEFAULT 0,
  employment_start int(11) unsigned NOT NULL DEFAULT 0,
  published_from int(11) unsigned NOT NULL DEFAULT 0,
  published_to int(11) unsigned NOT NULL DEFAULT 0,
  is_active tinyint(1) NOT NULL DEFAULT 1,
  contact_email varchar(255) NOT NULL DEFAULT '',
  attachments int(11) unsigned NOT NULL DEFAULT 0,
  categories int(11) unsigned NOT NULL DEFAULT 0,
  sorting int(11) NOT NULL DEFAULT 0,
  sys_language_uid int(11) NOT NULL DEFAULT 0,
  l10n_parent int(11) unsigned NOT NULL DEFAULT 0,
  l10n_source int(11) unsigned NOT NULL DEFAULT 0,
  l10n_diffsource mediumblob,
  hidden tinyint(1) NOT NULL DEFAULT 0,
  deleted tinyint(1) NOT NULL DEFAULT 0,
  tstamp int(11) unsigned NOT NULL DEFAULT 0,
  crdate int(11) unsigned NOT NULL DEFAULT 0,
  cruser_id int(11) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (uid),
  KEY parent (pid),
  UNIQUE KEY slug_language (slug, sys_language_uid, pid)
);

CREATE TABLE tx_aiscareer_domain_model_application (
  uid int(11) unsigned NOT NULL auto_increment,
  pid int(11) unsigned NOT NULL DEFAULT 0,
  job int(11) unsigned NOT NULL DEFAULT 0,
  first_name varchar(255) NOT NULL DEFAULT '',
  last_name varchar(255) NOT NULL DEFAULT '',
  email varchar(255) NOT NULL DEFAULT '',
  phone varchar(255) NOT NULL DEFAULT '',
  message text,
  cv_file int(11) unsigned NOT NULL DEFAULT 0,
  consent_privacy tinyint(1) NOT NULL DEFAULT 0,
  created_at int(11) unsigned NOT NULL DEFAULT 0,
  hidden tinyint(1) NOT NULL DEFAULT 0,
  deleted tinyint(1) NOT NULL DEFAULT 0,
  tstamp int(11) unsigned NOT NULL DEFAULT 0,
  crdate int(11) unsigned NOT NULL DEFAULT 0,
  cruser_id int(11) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (uid),
  KEY parent (pid)
);
